### ISSUE TITLE
[Request] Functionality use hicrep with .hic files

### ISSUE THREAD

**Issue by srcoulombe** [dejunlin/hicrep#10]
I have some .hic files I'd like to analyse with hicrep, but the current implementation is hard-coded to use files generated by Cooler. 
Are there any plans to extend hicrep's functionality to allow for .hic input files?

**Comment by dejunlin** [comment]
You can convert .hic to Cooler format using https://github.com/4dn-dcic/hic2cool. File format conversion is its own project due to the complexity of the binary formats and unlikely to be supported in general.
