### ISSUE TITLE
Should the input matrix be normalized for hicrep?

### ISSUE THREAD

**Issue by YiweiNiu** [dejunlin/hicrep#13]
Hi,

A quick question: should I feed the raw matrix or normalized matrix to hicrep? If the normalized matrix should be used, what method should be used for normalization, explicit or implicit (matrix-balancing)?

Sorry if the question is too naive. I am new to Hi-C data.

Thank you in advance.

**Comment by dejunlin** [comment]
The raw matrix should be used. There is a internal normalization step where the raw contact counts are divided by the total contact counts in the data.

**Comment by dejunlin** [comment]
Also, the count data type should be integer, which is the case in most Cooler files in a default setting unless you process the file somehow. Float type representation of raw count data might trigger numerical exception so it should be avoided

**Comment by YiweiNiu** [comment]
Thank you very much for the clarification. It help.
