### ISSUE TITLE
The chromosome order in output.SCC.txt

### ISSUE THREAD

**Issue by KunFang93** [dejunlin/hicrep#14]
Hi,

I was wondering if the chromosome order in output.SCC.txt is chr1, chr2,..,chr22, chrX, chrY (from top to bottom)? Thanks!

Best,
Kun

**Comment by dejunlin** [comment]
Generally no. The output list is in the same order as whatever in the input Cooler files. This code is ignorant of chromosome naming schemes and it assumes nothing on how the user order the chromosomes in the input. When you use `--chrNames` option, the output will be in the same order as the argument given to the option.

**Comment by dejunlin** [comment]
I just updated the Readme of this repo to be more explicit on this. Feel free to comment if you have other questions.

**Comment by KunFang93** [comment]
Understand~ Thanks for the explanation!
