### ISSUE TITLE
AssertionError: Input cool files have different number of bins

### ISSUE THREAD

**Issue by hiroyukikato911** [dejunlin/hicrep#17]
Hi,

Thanks for this wonderful tool.

I want to compare my .hic data with other downloaded .hic.
I used hic2cool to obtain .cool input but seems that there are difference in nbins.
HiC1.cool has "nbins": 3113 (1MB resolution)
HiC2.cool has "nbins": 3114 (1MB resolution)

Is there any way to fix this?
Any help is appreciated.

Best,

**Comment by dejunlin** [comment]
Hi, by definition, hicrep can only work on two contact matrices with the same underlying chromosome. It's likely that you have some upstream data processing error, e.g., different assembly or bin definition. I don't think this is a hicrep issue

**Comment by dejunlin** [comment]
Closing as this is not a hicrep issue. Feel free to open new issues if find other problems of using the code
