### ISSUE TITLE
Compare similarity using ICE-normalized cool files

### ISSUE THREAD

**Issue by zzhoujialu** [dejunlin/hicrep#19]
Great work! However, I have a specific requirement where I need to compare the similarity between Hi-C matrices from different batches. I have ICE-normalized cool files. I would like to know how to handle this type of data for my analysis.

Any suggestions or examples would be greatly appreciated.

Thank you in advance for your help!

**Comment by dejunlin** [comment]
If you go over the original HiCRep paper, you would see that the statistics involved in HiCRep doesn't work with ICE-normalized counts right out of the box. You'll probably have to do your own research to modify the original algorithm to fit your need. Good luck!
