### ISSUE TITLE
AssertionError: Contact matrix 2 of chromosome Y is empty

### ISSUE THREAD

**Issue by redjay8** [dejunlin/hicrep#20]
When I run the code using 2 .cool files rather than 2 .mcool files, there is an Assertion Error (AssertionError: Contact matrix 2 of chromosome Y is empty). However, when checking the two .cool files, there is data for chromosome Y. Why is there an error? Would just like to add that the same .mcool files show no error and works perfectly. Need an answer as soon as possible :) :)

**Checking to see if there is missing data**
chromosomes: ['M', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', 'X', 'Y'], binsize: 10000
M : (0, 2)
1 : (2, 24898)
2 : (24898, 49118)
3 : (49118, 68948)
4 : (68948, 87970)
5 : (87970, 106124)
6 : (106124, 123205)
7 : (123205, 139140)
8 : (139140, 153654)
9 : (153654, 167494)
10 : (167494, 180874)
11 : (180874, 194383)
12 : (194383, 207711)
13 : (207711, 219148)
14 : (219148, 229853)
15 : (229853, 240053)
16 : (240053, 249087)
17 : (249087, 257413)
18 : (257413, 265451)
19 : (265451, 271313)
20 : (271313, 277758)
21 : (277758, 282429)
22 : (282429, 287511)
X : (287511, 303116)
Y : (303116, 308839)

**Code**
from hicrep import hicrepSCC

h = 1

dBPMax = 500000

bDownSample = False

scc = hicrepSCC(cool1, cool2, h, dBPMax, bDownSample)

**Error Message**
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In[89], line 18
     13 bDownSample = False
     15 # compute the SCC score
     16 # this will result in a SCC score for each chromosome available in the data set
     17 # listed in the same order as the chromosomes are listed in the input Cooler files
---> 18 scc = hicrepSCC(cool1, cool2, h, dBPMax, bDownSample)

File ~/miniconda3/envs/jupyter/lib/python3.11/site-packages/hicrep/hicrep.py:177, in hicrepSCC(cool1, cool2, h, dBPMax, bDownSample, chrNames, excludeChr)
    174 assert mS1.shape[0] == mS1.shape[1],\
    175     "Contact matrix 1 of chromosome %s is not square" % (chrName)
    176 mS2 = getSubCoo(p2, bins2, chrName)
--> 177 assert mS2.size > 0, "Contact matrix 2 of chromosome %s is empty" % (chrName)
    178 assert mS2.shape[0] == mS2.shape[1],\
    179     "Contact matrix 2 of chromosome %s is not square" % (chrName)
    180 assert mS1.shape == mS2.shape,\
    181     "Contact matrices of chromosome %s have different input shape" % (chrName)

AssertionError: Contact matrix 2 of chromosome Y is empty

**Comment by dejunlin** [comment]
The data in `Checking to see if there is missing data` section doesn't tell you if you have data in any of the chromosomes but they are just segmentation of the genome in the unit of HiC bin. You'll get the same segmentation for the same genome assembly regardless of if you have data or not.
This implementation relies on the Cooler API to determine if a hic data has empty counts of a chromosome in a very straightforward manner so most likely you do have empty data. If not, try using another tool to extract the data in chromosome Y and you  can make a minimal reproducer and report it to the Cooler repo.

**Comment by dejunlin** [comment]
I forgot to mention that you could use the option `--excludeChr Y` to exclude the empty chromosome data if that's your intention
