### ISSUE TITLE
whether could output a data1_vs_data2.cool for downstream analysis?

### ISSUE THREAD

**Issue by JiaoLaboratory** [dejunlin/hicrep#21]
**Describe the bug**
A clear and concise description of what the bug is and include the details of any warnings or error messages.

**To Reproduce**
Steps to reproduce the behavior, including the full set of commands or the sequence of library function call that lead to the behavior :

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. ubuntu 16.04]
 - python Version [e.g. 3.8.1]
 - numpy Version [e.g. 1.6.1]
 - scipy Version [e.g. 1.6.3]
 - HiCRep Version [e.g. 22]

**Additional context**
If possible, post the link to the data used in the aforementioned example

Hi,dejunlin,
Thanks for your great tool. In fact I have two hic data, including  tissue1 and tissue2, and  I  want to compare the two data and get a tissue1_vs_tissue2.cool for further analysis, Could you help me?

**Comment by dejunlin** [comment]
Hi, when you said "compare the two data", I assume you meant doing so by running hicrep. If so, you need to prepare the files: tissue1.cool and tissue2.cool (or the *.mcool files). If you data are in *.hic format, you can use this tool: https://github.com/4dn-dcic/hic2cool to convert them to .cool or .mcool format. After you get the cool/mcool files, follow the instruction on the README to run the command line tool like this (quoting from the README):

To use as a command line tool, install this package by
```
pip install hicrep
```
then run 
```
hicrep mydata1.mcool mydata2.mcool outputSCC.txt --binSize 100000 --h 1 --dBPMax 500000 
```
when passing in an `.mcool` file with multiple binsizes or 
```
hicrep mydata1.cool mydata2.cool outputSCC.txt --h 1 --dBPMax 500000 
```
when passing in a `.cool` file with a single bultin binsize. The output `outputSCC.txt` has a list of SCC scores for each chromosome in the input. The output SCC scores are listed in the same order as the chromosomes are listed in the input Cooler files.

**Comment by dejunlin** [comment]
Closing but feel free to comment or post more questions
