### ISSUE TITLE
hicrepcm to generate clustermap of hicrep SCC scores

### ISSUE THREAD

**Issue by yardimcilab** [dejunlin/hicrep#22]
We have created a new package, `hicrepcm`, which computes hicrep SCC scores for an arbitrary number of input contact matrices and outputs them as a clustermap. You may be interested in linking to this project in the readme for hicrep itself. We find this a convenient way to generate and share results from hicrep. Here is the [github repo](https://github.com/yardimcilab/hicrepcm).

Thanks for your great work on this project.

**Comment by dejunlin** [comment]
Hi, thanks for letting me know about hicrepcm. The plot looks very nice! I added a section in the README to link to it.

BTW, are you from Gurkan Yardimci lab?
