### ISSUE TITLE
Existing python implementation

### ISSUE THREAD

**Issue by cmdoret** [dejunlin/hicrep#4]
Hello,

It's great you're doing this, I just wanted to let you know I already reimplemented it in python last year with support for cool files / sparse matrices: https://github.com/cmdoret/hicreppy

I saw that you are writing a paper where you compare your python implementation to the original hicrep package. Perhaps you could consider including my implementation in your comparisons ?

If some parts of my implementations happen to be more efficient, you are welcome to use them in your code.

I suspect results from my implementation differ more from the original package as I took a few liberties. For example, it returns the average SCC of all chromosomes weighted by their lengths, instead of each SCC independently.

Best, 
Cyril

**Comment by dejunlin** [comment]
Hi Cyril, Thank you for pointing out your implementation! We have included a comparison of our version to your version in Figure 2 of the supplement and some discussion in the text above Figure 2: https://academic.oup.com/bioinformatics/advance-article/doi/10.1093/bioinformatics/btab097/6133255 Incidentally, our current version appears to be exponentially faster and uses less memory. Your are also welcome to use our code in GPL-licensed projects.

I'm closing this for now but feel free to comment if you have other questions!

**Comment by cmdoret** [comment]
That's great news ! Thanks for doing the comparison, and congrats for the publication, I'll start using your implementation :)
